"""added trelationship

Revision ID: 1cd8c754548b
Revises: c53ef767ec40
Create Date: 2024-01-11 08:17:50.771910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cd8c754548b'
down_revision = 'c53ef767ec40'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
