"""seeded data

Revision ID: 4a5cebc8c0f0
Revises: 1cd8c754548b
Create Date: 2024-01-11 08:41:49.347965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a5cebc8c0f0'
down_revision = '1cd8c754548b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
