"""added train table

Revision ID: 7516c7e210f7
Revises: a7bb36db723d
Create Date: 2024-01-10 14:34:48.802720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7516c7e210f7'
down_revision = 'a7bb36db723d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
