"""added stations table

Revision ID: 99c72d07443a
Revises: 7516c7e210f7
Create Date: 2024-01-10 14:35:47.680541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99c72d07443a'
down_revision = '7516c7e210f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
