"""create database

Revision ID: a7bb36db723d
Revises: 
Create Date: 2024-01-10 14:33:49.671675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7bb36db723d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_name', sa.String(), nullable=True),
    sa.Column('Location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('train_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arrival_time', sa.String(), nullable=True),
    sa.Column('depature_time', sa.String(), nullable=True),
    sa.Column('train_id', sa.Integer(), nullable=True),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name=op.f('fk_train_schedule_station_id_stations')),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], name=op.f('fk_train_schedule_train_id_trains')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('train_schedule')
    op.drop_table('trains')
    op.drop_table('stations')
    # ### end Alembic commands ###
