"""added trainschedule

Revision ID: c53ef767ec40
Revises: 99c72d07443a
Create Date: 2024-01-10 14:37:21.229393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c53ef767ec40'
down_revision = '99c72d07443a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
